export interface ItemShow {
        Id: number,
        Name: string,
        NCMId?: string,
        CategoryId: number,
        CreatedDate: Date,
        LastModifyDate: Date,
        CreatedBy: number,
        LastModifyBy: 4,
        CompanyId: number,
        ItemExternalId: number,
        Amount: string,
        EANId?: any,
        MakeServicesTax: boolean,
        QueueId: number,
        EAN: any,
        Queue: string,
        Image:string,
        Delivered:string,
        Description:string
}